version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./data:/initdb
    container_name: todo-database
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TodoApiSqlPass123!
      - MSSQL_PID=Developer
  api:
    container_name: todo-api
    build: ./ToDo.Api
    ports:
      - 5501:5501
    depends_on:
      - db